CarDealership/CarDealership/Controllers/InventoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices;
using System.Web;
using System.Web.Mvc;
using CarDealership.BLL;
using CarDealership.Models;

namespace CarDealership.Controllers
{
    public class InventoryController : Controller
    {
        private Manager _manager = ManagerFactory.CreateManager();

        [HttpGet]
        public ActionResult New()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Used()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Details(int id)
        {
            return View(_manager.GetVehicleById(id));
        }
    }
}

CarDealership/CarDealership/Controllers/ReportsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CarDealership.BLL;
using CarDealership.Models;

namespace CarDealership.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ReportsController : Controller
    {
        Manager _manager = ManagerFactory.CreateManager();

        // GET: Reports
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Sales()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Inventory()
        {
            var model = new InventoryReportVM();

            model.NewInventory = _manager.GetNewInventoryList();
            model.UsedInventory = _manager.GetUsedInventoryList();
            return View(model);
        }
    }
}

CarDealership/CarDealership/Controllers/SalesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using CarDealership.BLL;
using CarDealership.Models;
using Microsoft.ApplicationInsights.WindowsServer.Channel.Implementation;

namespace CarDealership.Controllers
{
    [Authorize(Roles = "Admin, Sales")]
    public class SalesController : Controller
    {
        private Manager _manager = ManagerFactory.CreateManager();

        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Purchase(int id)
        {
            var model = new SaleVm();
            model.Vehicle = _manager.GetVehicleById(id);
            model.Sale = new Sale();
            model.Sale.VehicleId = model.Vehicle.Id;
            model.Sale.ListPrice = model.Vehicle.Price;
            return View(model);
        }

        [HttpPost]
        public ActionResult Purchase(Sale sale)
        {
            if (sale.Email == null && sale.Phone == null)
            {
                ModelState.AddModelError("Email, Phone", "Phone or Email is required.");
            }
            if (!string.IsNullOrEmpty(sale.Email))
            {
                if (Regex.IsMatch(sale.Email, @"^[a-zA-Z0-9@\.]+$") == false)
                {
                    ModelState.AddModelError("Email", "Email must be in correct format.");
                }
            }
            if (sale.Name == null)
            {
                ModelState.AddModelError("Name", "Name is required.");
            }
            if (sale.City == null)
            {
                ModelState.AddModelError("City", "City is required.");
            }
            if (sale.Zipcode.Length != 5 || Regex.IsMatch(sale.Zipcode, @"^[0-9]+$") == false)
            {
                ModelState.AddModelError("Zipcode", "Invalid Zipcode.");
            }
            if (sale.PurchasePrice < (sale.ListPrice * .95M))
            {
                ModelState.AddModelError("PurchasePrice", "Actual price cannot be less than 95% of list price.");
            }
            if (ModelState.IsValid)
            {
                sale.SalesPerson = User.Identity.Name;
                _manager.PostSale(sale);
                return RedirectToAction("Index");
            }

            var model = new SaleVm();

            model.Vehicle = _manager.GetVehicleById(sale.VehicleId);
            model.Sale = sale;

            return View(model);
        }
    }
}

CarDealership/CarDealership/Views/Reports/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Reports</h2>

@Html.ActionLink("Inventory Report", "Inventory", "Reports") <br/>
@Html.ActionLink("Sales Report", "Sales", "Reports")

CarDealership/CarDealership/Views/Reports/Inventory.cshtml
@model CarDealership.Models.InventoryReportVM

@{
    ViewBag.Title = "Inventory";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Inventory Report</h2>

<div class="col-md-12">
    <div class="col-md-6">
        <h4>New Vehicles</h4>
        <table class="table table-striped table-bordered">
            <tr>
                <th>Year</th>
                <th>Make</th>
                <th>Model</th>
                <th>Count</th>
                <th>Stock Value</th>
            </tr>

            @foreach (var line in Model.NewInventory)
            {
                <tr>
                    <td>
                        @line.Year
                    </td>
                    <td>
                        @line.Make
                    </td>
                    <td>
                        @line.Model
                    </td>
                    <td>
                        @line.Count
                    </td>
                    <td>
                        @line.StockValue.ToString("C0")
                    </td>
                </tr>
            }
        </table>
    </div>
</div>


<div class="col-md-12">
    <div class="col-md-6">
        <h4>Used Vehicles</h4>
        <table class="table table-striped table-bordered">
            <tr>
                <th>Year</th>
                <th>Make</th>
                <th>Model</th>
                <th>Count</th>
                <th>Stock Value</th>
            </tr>

            @foreach (var line in Model.UsedInventory)
            {
                <tr>
                    <td>
                        @line.Year
                    </td>
                    <td>
                        @line.Make
                    </td>
                    <td>
                        @line.Model
                    </td>
                    <td>
                        @line.Count
                    </td>
                    <td>
                        @line.StockValue.ToString("C0")
                    </td>
                </tr>
            }
        </table>
    </div>
</div>

CarDealership/CarDealership/Views/Reports/Sales.cshtml
@model CarDealership.Models.SalesReport

@{
    ViewBag.Title = "Sales";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="col-md-12">
    <h2>Sales</h2>

    <form class="form-horizontal salesReportForm col-md-9">
        <fieldset>
            <div class="form-group col-md-4">
                <label class="col-md-3 control-label" for="userSort">User</label>
                <div class="col-md-9">
                    <select id="userSort" name="userSort" class="form-control">
                        <option value="">Default</option>
                        <option value="temp">temp</option>
                        <option value="Test User">Test User</option>
                    </select>
                </div>
            </div>
            <div class="form-group col-md-4">
                <label class="col-md-3 control-label" for="startDate">Start Date</label>
                <div class="col-md-9">
                    <input id="startDate" name="startDate" type="text" placeholder="Enter start date for report: mm/dd/yyyy" class="form-control input-md">
                </div>
            </div>
            <div class="form-group col-md-4">
                <label class="col-md-3 control-label" for="endDate">End Date</label>
                <div class="col-md-9">
                    <input id="endDate" name="endDate" type="text" placeholder="Enter end date for report: mm/dd/yyyy" class="form-control input-md">
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-4 reportSearch">
                    <button id="reportSearch" name="reportSearch" class="btn btn-primary">Search</button>
                </div>
            </div>
        </fieldset>
    </form>
</div>
<div class="col-md-12">
    <div class="col-md-6">
        <table id="searchResults" class="table table-striped table-bordered">
            <h4>Search Results</h4>
            <tr>
                <th>User</th>
                <th>Total Sales</th>
                <th>Total Vehicles</th>
            </tr>
        </table>
    </div>
</div>
<div id="errorMessages"></div>