Capstone/CookieBlog/CookieBlog/Controllers/BlogPostController.cs
using CookieBlog.BLL;
using CookieBlog.Models;
using CookieBlog.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Security.Policy;
using System.Web;
using System.Web.Mvc;
using System.Windows.Forms;

namespace CookieBlog.Controllers
{

    public class BlogPostController : Controller
    {
        private Manager _manager = ManagerFactory.CreateManager();

        [HttpGet]
        public ActionResult Index()
        {
            return RedirectToAction("Home");
        }

        [HttpGet]
        public ActionResult Home()
        {
            var model = _manager.GetAllBlogPostTagsVm();

            return View(model);
        }

        [HttpPost]
        public ActionResult Home(BlogPostTagsVM blogTagVM)
        {
            return View();
        }

        [HttpGet]
        public ActionResult Details(int blogid)
        {
            BlogPost model = _manager.GetAnyBlogPost(blogid);
            return View(model);
        }

        [HttpPost]
        public ActionResult Details(BlogPost PostVM)
        {
            return View();
        }

        [HttpGet]
        [Authorize(Roles="Admin, Contributor")]
        public ActionResult Add()
        {
            CreateBlogPostVM model = new CreateBlogPostVM()
            {
                blogPost = new BlogPost(),
                categoryList = _manager.GetAllCategories(),
            };

            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = "Admin, Contributor")]
        public ActionResult Add(CreateBlogPostVM model, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    string filename = "Image" + DateTime.Now.ToString("yy-MM-dd-hh-mm") + ".jpg";

                    string _path = Path.Combine(Server.MapPath("~/uploads"), filename);

                    if (!System.IO.File.Exists(_path))
                    {
                        System.IO.File.Create(_path).Close();
                    }

                    file.SaveAs(_path);

                    model.blogPost.BlogImage = "/uploads/" + filename;
                }
                model.blogPost.Author = User.Identity.Name;
                BlogPost sampleBlogPost = _manager.CreateNewBlogPost(model.blogPost);
                return RedirectToAction("Details", new { blogid = sampleBlogPost.BlogId });
            }
            else
            {
                return View("Add", model);
            }
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int id)
        {
            BlogPost model = _manager.GetAnyBlogPost(id);
            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(BlogPost model)
        {
            string filename = model.BlogImage;

            if(filename != null)
            {
                string _path = Path.Combine(Server.MapPath("~/uploads"), filename);

                if (System.IO.File.Exists(_path))
                {
                    System.IO.File.Delete(_path);
                }
            }

            _manager.Delete(model.BlogId);
            return RedirectToAction("Home");
        }

        [HttpGet]
        [Authorize(Roles = "Admin, Contributor")]
        public ActionResult Edit(int blogid)
        {
            CreateBlogPostVM model = new CreateBlogPostVM()
            {
                blogPost = _manager.GetAnyBlogPost(blogid),
                categoryList = _manager.GetAllCategories(),
            };
            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = "Admin, Contributor")]
        public ActionResult Edit(CreateBlogPostVM model, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {

                if (file != null)
                {
                    string filename = "Image" + DateTime.Now.ToString("yy-MM-dd-hh-mm") + ".jpg";

                    string _path = Path.Combine(Server.MapPath("~/uploads"), filename);

                    if (System.IO.File.Exists(model.blogPost.BlogImage))
                    {
                        System.IO.File.Delete(model.blogPost.BlogImage);
                    }
                    if (!System.IO.File.Exists(_path))
                    {
                        System.IO.File.Create(_path).Close();
                    }
                    file.SaveAs(_path);

                    model.blogPost.BlogImage = "/uploads/" + filename;
                }

                if (User.IsInRole("Contributor"))
                {
                    model.blogPost.IsApproved = false;
                }
                BlogPost sampleBlogPost = _manager.UpdateBlogPost(model.blogPost);
                return RedirectToAction("Details", new { blogid = sampleBlogPost.BlogId });
            }
            else
            {
                return View("Edit", model);
            }
        }

        [HttpGet]
        public ActionResult SearchResults(string searchText, string search)
        {
            List<BlogPost> model = new List<BlogPost>();
            List<BlogPost> blogPostList = _manager.GetAllBlogPost();

            if (search == "Category")
            {
                foreach (var item in blogPostList)
                {
                    if (item.Category.Contains(searchText))
                    {
                        model.Add(item);
                    }
                }
            }
            else if (search == "Title")
            {
                foreach (var item in blogPostList)
                {
                    if (item.BlogTitle.Contains(searchText))
                    {
                        model.Add(item);
                    }
                }
            }
            else
            {
                foreach (var item in blogPostList)
                {
                    if (item.BlogTags.Contains(searchText))
                    {
                        model.Add(item);
                    }
                }
            }
            return View(model);
        }

        [HttpGet]
        public ActionResult UnApprovedBlogs()
        {
            var model = _manager.GetAllBlogPost();
            return View(model);
        }
    }
}

Capstone/CookieBlog/CookieBlog/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title Kyle's Kooky Cookie Blog</title>
    <link href="~/Content/CookeBlog.css" rel="stylesheet" />
    <link href="~/Content/LayoutStyleSheet.css" rel="stylesheet" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script src="https://cloud.tinymce.com/stable/tinymce.min.js"></script>
    <script>
tinyMCE.init({
    // General options
    mode: "textareas",
    theme: "modern",
    // Theme options
    theme_advanced_buttons1: "newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,styleselect,formatselect,fontselect,fontsizeselect",
    theme_advanced_buttons2: "cut,copy,paste,pastetext,pasteword,|, search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
    theme_advanced_buttons3: "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
    theme_advanced_buttons4: "insertlayer,moveforward,movebackward,absolute,|,styleprops,spellchecker,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,template,blockquote,pagebreak,|,insertfile,insertimage",
    theme_advanced_toolbar_location: "top",
    theme_advanced_toolbar_align: "left",
    theme_advanced_statusbar_location: "bottom",
    theme_advanced_resizing: true

});</script>

    <link class="jsbin" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1/themes/base/jquery-ui.css" rel="stylesheet" type="text/css" />
    <script class="jsbin" src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
    <script class="jsbin" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.0/jquery-ui.min.js"></script>
    <meta charset=utf-8 />
    <title>JS Bin</title>
    <!--[if IE]>
        <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <style>
        article, aside, figure, footer, header, hgroup,
        menu, nav, section {
            display: block;
        }
    </style>

</head>
<body id="backgroundEdit">
<div id="navEdit" class="navbar navbar-inverse navbar-fixed-top">

        <div class="navbar-header col-md-2">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Kyle's Kooky Cookie Blog", "Home", "BlogPost", new {area = ""}, new {@class = "navbar-brand", @id = "HomeLink"})
        </div>
    <div id="SearchType" class="navbar-collapse collapse col-md-4">
        <ul class="nav navbar-nav">
            <li class="dropdown">
                <div class="dropdown">
                    <div class="form-group">
                        <select class="form-control" id="search">
                            <option>Search By Title</option>
                            <option>Search By Tag</option>
                            <option>Search By Category</option>
                        </select>
                    </div>
                </div>
            </li>

            <li id="searchText">
                <div>
                    <input id="whiteSpace" type="text" placeholder="Search" name="searchText" value="" />
                </div>
            </li>

            <li class="col-md-2">
                <button id="searchButton" class="btn btn-default">Get Kooky</button>
            </li>
        </ul>
    </div>
    <div id="userNav" class="navbar-collapse collapse col-md-offset-6">
                @if (User.Identity.GetUserName() != "")
                {
                    <span id="welcomeUser">
                        Welcome @User.Identity.GetUserName()!
                    </span>

                }
                else
                {
                    <span id="welcomeUser">
                        Welcome Kooky Friend!
                    </span>
                }
                @if (User.IsInRole("Contributor") || User.IsInRole("Admin"))
                {
                    <button id="logoffButton" class="btn btn-default">LogOff</button>
                    if (User.IsInRole("Admin"))
                    {
                        <button class="btn btn-default">
                            @Html.ActionLink("Create New User", "Register", "Account")
                        </button>
                    }
                    <button class="btn btn-default">
                        @Html.ActionLink("Write Blog", "Add", "BlogPost")
                    </button>
                    <button class="btn btn-default">
                        @Html.ActionLink("View Unapproved Blogs", "UnApprovedBlogs", "BlogPost")
                    </button>
                }
                else
                {
                    <button class="btn btn-default">
                        @Html.ActionLink("Login", "Login", "Account")
                    </button>
                }
    </div>
</div>
<div id="shadowBackground" class="container body-content" style="background-color: whitesmoke; min-height: 800px;">
    @RenderBody()
</div>
    <hr/>

    <footer>
        <p>&copy; @DateTime.Now.Year - Kyle's Kooky Cookie Blog</p>
    </footer>


@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", required: false)
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="~/Scripts/CookieBlog.js"></script>
@*<script src="~/Scripts/typeahead.js/bloodhound.js"></script>
    <script src="~/Scripts/typeahead.js/bloodhound.min.js"></script>
    <script src="~/Scripts/typeahead.js/typeahead.bundle.js"></script>
    <script src="~/Scripts/typeahead.js/typeahead.bundle.min.js"></script>
    <script src="~/Scripts/typeahead.js/typeahead.jquery.js"></script>
    <script src="~/Scripts/typeahead.js/typeahead.jquery.min.js"></script>*@
<script src="~/Scripts/TagsInput.js"></script>
</body>
</html>